[package]
name        = "pdf-platform-plugin-sdk"
description = "Rust guest SDK for PDF Platform plugins. [ADR-014, ADR-015, M11]"
version     = "1.0.0"
edition     = "2021"
license     = "GPL-3.0-or-later"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde       = { version = "1", features = ["derive"], optional = true }
serde_json  = { version = "1", optional = true }

[features]
default = []
host    = ["serde", "serde_json"]
